# Generated by Django 2.1.7 on 2019-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0002_remove_users_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='interests',
            field=models.CharField(default='0,0,0,0', max_length=50),
        ),
    ]
