# Generated by Django 2.1.7 on 2019-04-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0004_questionimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimages',
            name='question',
        ),
        migrations.DeleteModel(
            name='questionImages',
        ),
    ]
