# Generated by Django 2.1.7 on 2019-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0008_auto_20190428_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verified',
            field=models.CharField(default='verifiy', max_length=10),
        ),
    ]
