# Generated by Django 2.1.7 on 2019-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0012_auto_20190429_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='bestanswer',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
