# Generated by Django 2.1.7 on 2019-04-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0014_auto_20190429_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='mentioned_users',
        ),
    ]
