# Generated by Django 2.1.7 on 2019-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0015_remove_answer_mentioned_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='change_theme',
        ),
        migrations.AddField(
            model_name='users',
            name='mode_path',
            field=models.TextField(default='/static/QuestionAndAnswer/css/modes/dark-mode.css'),
        ),
        migrations.AddField(
            model_name='users',
            name='theme_path',
            field=models.TextField(default='/static/QuestionAndAnswer/css/themes/default-theme.css'),
        ),
    ]
