# Generated by Django 2.1.7 on 2019-06-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0018_auto_20190610_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='badages',
            new_name='achievement',
        ),
        migrations.AlterUniqueTogether(
            name='achievements',
            unique_together=set(),
        ),
    ]
