# Generated by Django 2.1.7 on 2019-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0019_auto_20190611_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='achievement_count',
            field=models.IntegerField(default=0),
        ),
    ]
