# Generated by Django 2.1.7 on 2019-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAndAnswer', '0020_users_achievement_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verify_code',
            field=models.CharField(default='verify', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='verified',
            field=models.BooleanField(default=0),
        ),
    ]
